[package]
name = "hello-world"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
lambda_http.workspace = true
tokio.workspace = true

