[workspace]
members = ["lambdas/hello-world"]
resolver = "2"

[workspace.package]
description = "An AWS Lambda blog API written in Rust"
version = "0.0.12"
edition = "2021"
license = "MIT"
repository = "https://github.com/londonbrown/blog-lambdas"

[workspace.dependencies]
lambda_http = "0.14.0"
tokio = { version = "1", features = ["macros"] }
