[workspace]
members = ["lambdas/hello-world", "lambdas/get-post"]
resolver = "2"

[workspace.package]
description = "An AWS Lambda blog API written in Rust"
version = "0.0.23"
edition = "2021"
license = "MIT"
repository = "https://github.com/londonbrown/blog-lambdas"

[workspace.dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.67.0"
lambda_http = "0.14.0"
serde_json = "1.0"
serde_dynamo = "4.2.14"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.41"
