[workspace]
members = ["lambdas/hello-world"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
lambda_http = "0.14.0"
tokio = { version = "1", features = ["macros"] }
